image: cypress/browsers:node16.18.0-chrome90-ff88

before_script:
  - npm install yarn
  - yarn install
  - yarn start &

cypress:
  stage: test
  only:
    - main
  script:
    - yarn add cypress
    - sleep 5
    - yarn test

ddosify:
  stage: test
  only:
    - main
  script:
    - ./ddosify.sh

    

