cypress:
  image: docker.io/bonnyophelie/tickethack
  stage: test
  only:
    - main
  script:
    - npm install yarn
    - yarn install
    - yarn start &
    - yarn add cypress
    - sleep 5
    - yarn test

ddosify:
  image: alpine:latest
  stage: test
  only:
    - main
  script:
    - wget https://github.com/ddosify/ddosify/releases/latest/download/ddosify_amd64.apk
    - apk add --allow-untrusted ddosify_amd64.apk
    - apk add yarn
    - yarn start &
    - sleep 10
    - ddosify -t http://localhost:3000