before_script:
  - npm install yarn
  - yarn install

cypress:
  image: cypress/browsers:node16.18.0-chrome90-ff88
  stage: test
  only:
    - main
  script:
    - yarn add cypress
    - yarn start &
    - yarn test

    

