trigger:
  - main

pool:
  name: Azure Pool

steps:
  - script: | 
      docker login -u $(DOCKER_REGISTRY_USER) -p $(DOCKER_PAT)
      docker build -t bonnyophelie/tickethack --no-cache --build-arg url=$(CONNECTION_STRING) .
      docker push bonnyophelie/tickethack
    displayName: 'docker login, build and push'

  - script: | 
      docker run --name tickethack -p 3000:3000 -d bonnyophelie/tickethack
      yarn add cypress --dev
      yarn run cypress run 
    displayName: 'Run backend tests with Cypress and docker image'

  - script: | 
      ddosify -t http://localhost:3000 
    displayName: 'Run ddosify'
  
  - script: | 
      docker stop tickethack && docker rm tickethack && docker rmi bonnyophelie/tickethack
    displayName: 'Stop delete container and remove image'
