trigger:
  - main

pool:
  name: Azure Pool

jobs:
  - job: backend_test
    steps:
    - script: | 
        yarn install 
        yarn start & 
        yarn test 
      displayName: 'Run backend tests'

  - job: ddosify
    steps:
    - script: | 
        yarn install 
        yarn start & 
        wget https://github.com/ddosify/ddosify/releases/latest/download/ddosify_amd64.deb 
        dpkg -i ddosify_amd64.deb ddosify -t http://localhost:3000 
      displayName: 'Run ddosify'
